# Generated by Django 5.0.1 on 2025-07-03 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telegram_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_latitude', models.FloatField(help_text='Pickup location latitude')),
                ('pickup_longitude', models.FloatField(help_text='Pickup location longitude')),
                ('pickup_address', models.TextField(null=True)),
                ('delivery_latitude', models.FloatField(help_text='Delivery location latitude')),
                ('delivery_longitude', models.FloatField(help_text='Delivery location longitude')),
                ('delivery_address', models.TextField(null=True)),
                ('distance_km', models.FloatField(null=True)),
                ('image', models.CharField(help_text='Optional image for the order')),
                ('map', models.TextField(null=True)),
                ('pickup_comment', models.TextField(blank=True, help_text='Additional comment for the pickup', null=True)),
                ('delivery_comment', models.TextField(blank=True, help_text='Additional comment for the delivery', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('order_price', models.DecimalField(decimal_places=2, help_text='Total price of the order', max_digits=10)),
                ('delivery_price', models.DecimalField(decimal_places=2, help_text='Delivery fee', max_digits=10)),
                ('payment_by', models.CharField(choices=[('user', 'Paid by User'), ('courier', 'Paid by Courier')], help_text='Who will pay the delivery price', max_length=10)),
                ('deliver_payment_by', models.CharField(choices=[('user', 'Paid by User'), ('customer', 'Paid by Customer')], help_text='Who will pay the product price', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='telegram_users.telegramusers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='telegram_users.telegramusers')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
