# Generated by Django 5.0.1 on 2025-07-03 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('telegram_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='courier',
        ),
        migrations.RemoveField(
            model_name='order',
            name='deliver_payment_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_comment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_latitude',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_longitude',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='distance_km',
        ),
        migrations.RemoveField(
            model_name='order',
            name='map',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pickup_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pickup_comment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pickup_latitude',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pickup_longitude',
        ),
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.CharField(max_length=100, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='order',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='telegram_users.telegramusers', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='order',
            name='image',
            field=models.CharField(verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('closed', 'Закрыто'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='telegram_users.telegramusers', verbose_name='Пользователь'),
        ),
    ]
